apiVersion: apps/v1
kind: Deployment
metadata:
    name: mydeployment
spec:
    replicas: 3
    selector: 
        matchLabels:
            env: note-app
    template: 
        metadata: 
            name: dep-pod
            labels: 
                env: note-app
        spec: 
            containers:
            - name: dep-cont
              image: chethanbrp/mynote-app:latest
              ports:
              - containerPort: 8000
